# Generated by Django 2.0.7 on 2018-07-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20180708_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='front',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='informacion',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
