# Generated by Django 2.0.7 on 2018-07-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20180708_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='front',
            options={'verbose_name_plural': 'front'},
        ),
        migrations.AlterModelOptions(
            name='informacion',
            options={'verbose_name_plural': 'informacion'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'usuarios'},
        ),
    ]
