# Generated by Django 2.0.7 on 2018-07-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20180708_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front',
            name='titulo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
