# Generated by Django 2.0.7 on 2018-07-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20180708_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front',
            name='informacion_adicional',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
